version: "3.8"
services:
  elevate-cv-api:
    build: .
    image: ${DOCKER_IMAGE}:${BUILD_NUMBER}
    container_name: elevate-cv-api
    restart: always
    ports:
      - "2200:2200"
    env_file:
      - .env
    # CRITICAL for low-RAM
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - elevate-network

networks:
  elevate-network:
    driver: bridge
